name: Dependabot PR Check
on:
  push:
    branches:
      - main

jobs:
  check-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - run: echo "PR created by Dependabot ✅"
